"""empty message

Revision ID: 2d73f3c3f648
Revises: b1f2e9882a22
Create Date: 2024-11-27 19:26:01.768488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d73f3c3f648'
down_revision = 'b1f2e9882a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puzzleLetters', sa.String(), nullable=True))
        batch_op.drop_column('puzzleWord')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puzzleWord', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('puzzleLetters')

    # ### end Alembic commands ###
