"""empty message

Revision ID: 8f806c83946c
Revises: 05a386d669e5
Create Date: 2024-12-02 16:34:56.963158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f806c83946c'
down_revision = '05a386d669e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_table',
    sa.Column('wordId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('wordId'),
    sa.UniqueConstraint('wordId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_table')
    # ### end Alembic commands ###
