"""initial migration

Revision ID: b1f2e9882a22
Revises: 
Create Date: 2024-11-27 17:08:17.767099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f2e9882a22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle',
    sa.Column('puzzleId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puzzleWord', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('puzzleId'),
    sa.UniqueConstraint('puzzleId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzle')
    # ### end Alembic commands ###
